apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallos.fullname" . }}
  labels:
    {{- include "wallos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wallos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wallos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wallos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.database.initialize }}
      initContainers:
        - name: init-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              # Check if database exists
              if [ ! -f /var/www/html/db/wallos.db ]; then
                echo "Initializing database..."
                # Copy the empty database
                if [ -f /var/www/html/db/wallos.empty.db ]; then
                  cp /var/www/html/db/wallos.empty.db /var/www/html/db/wallos.db
                  echo "Database file created."
                else
                  echo "Warning: wallos.empty.db not found, creating empty database file"
                  touch /var/www/html/db/wallos.db
                fi
                # Set proper permissions
                chown www-data:www-data /var/www/html/db/wallos.db
                chmod 644 /var/www/html/db/wallos.db
                echo "Database initialization complete."
              else
                echo "Database already exists, skipping initialization."
              fi
          volumeMounts:
            {{- if .Values.persistence.db.enabled }}
            - name: db-storage
              mountPath: {{ .Values.persistence.db.mountPath }}
            {{- end }}
          securityContext:
            runAsUser: 0
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.db.enabled }}
            - name: db-storage
              mountPath: {{ .Values.persistence.db.mountPath }}
            {{- end }}
            {{- if .Values.persistence.logos.enabled }}
            - name: logos-storage
              mountPath: {{ .Values.persistence.logos.mountPath }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.db.enabled }}
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "wallos.fullname" . }}-db
        {{- end }}
        {{- if .Values.persistence.logos.enabled }}
        - name: logos-storage
          persistentVolumeClaim:
            claimName: {{ include "wallos.fullname" . }}-logos
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
