# Default values for mk-stream.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Application metadata
nameOverride: ""
fullnameOverride: ""

# Image configuration
image:
  repository: soli0222/mk-stream
  tag: "2.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

# Pod security context
podSecurityContext: {}
  # fsGroup: 2000

# Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Deployment configuration
replicaCount: 1

# Resource limits and requests
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Secret configuration (OnePassword)
onePassword:
  enabled: false
  itemPath: "vaults/Kubernetes/items/mk-stream-secret"

# Environment variables from secrets
secrets:
  # Name of the secret containing application secrets
  secretName: ""
  # Environment variables to load from secret
  env:
    - name: TOKEN
      key: TOKEN

# Additional environment variables (not from secrets)
env:
  - name: HOST
    value: "example.tld"

# Health checks
livenessProbe: {}
  # httpGet:
  #   path: /health
  #   port: http
  # initialDelaySeconds: 30
  # periodSeconds: 10

readinessProbe: {}
  # httpGet:
  #   path: /ready
  #   port: http
  #   initialDelaySeconds: 5
  #   periodSeconds: 5