apiVersion: v1
kind: Service
metadata:
  name: {{ include "flow-sight.fullname" . }}-frontend
  labels:
    {{- include "flow-sight.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "flow-sight.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
