apiVersion: v2
name: misskey
description: A Helm chart for Misskey - A decentralized social networking platform
type: application
version: 0.1.3
# renovate: image=misskey/misskey
appVersion: "2026.3.2"
