{{- if .Values.onePassword.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "subscription-manager.fullname" . }}-credentials
  labels:
    {{- include "subscription-manager.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onePassword.itemPath | quote }}
{{- end }}
